
export default {
  GOOGLE_MAPS_API_KEY: "AIzaSyBdfX8epSZcNT3IqlC8bdjby5MzQZK0-S8",
  WP_REST_API_BASE_URL: "https://fluxit.be/react/reportmanagerv2/wp-json/",
  wpApiToken: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvZmx1eGl0LmJlXC9yZWFjdFwvcmVwb3J0bWFuYWdlcnYyIiwiaWF0IjoxNTI2MTQ5NDQwLCJuYmYiOjE1MjYxNDk0NDAsImV4cCI6NjMxMTM4NTIwMCwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMiJ9fX0.F2TKpGgCgNARh02yrDrPQEdIBKVrk-vtFbnndGph61w"
}